name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Generate build ID for PR
        if: startsWith(github.ref, 'refs/pull')
        run: |
          pr_ref="${GITHUB_REF_NAME%%/*}"
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "CONTAINER_ID=${pr_ref}-${sha}-${ts}" >> $GITHUB_ENV
      - name: Generate build ID for master
        if: github.ref == 'refs/heads/master'
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "CONTAINER_ID=${sha}-${ts}" >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: kubectl-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test kubectl installation
        run: |
          echo "Testing kubectl is installed..."
          docker run --rm kubectl-image:latest kubectl version --client
          echo "✅ kubectl test passed"
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: b354d443-d632-4d61-8ee8-2abc2c7baf23 # DTS Shared GitHub Actions ACR Publisher 1
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: 'ACR Login'
        run: |
          az acr login --name hmctsprod
      - name: 'Build and push PR image to HMCTSPROD'
        if: startsWith(github.ref, 'refs/pull')
        run: |
          docker tag kubectl-image:latest hmctsprod.azurecr.io/hmcts-kubectl/kubectl:pr-$CONTAINER_ID
          docker push hmctsprod.azurecr.io/hmcts-kubectl/kubectl:pr-$CONTAINER_ID
      - name: 'Build and push prod image to HMCTSPROD'
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag kubectl-image:latest hmctsprod.azurecr.io/hmcts-kubectl/kubectl:prod-$CONTAINER_ID
          docker push hmctsprod.azurecr.io/hmcts-kubectl/kubectl:prod-$CONTAINER_ID
