name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 0c90bba4-bee6-42d1-8398-dedede1319d1 # DTS Platform Operations GitHub Actions ACR Publisher 2
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true

      - name: 'ACR Login'
        run: |
          az acr login --name hmctsprod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: kubectl-image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test kubectl installation
        run: |
          echo "Testing kubectl is installed..."
          docker run --rm kubectl-image:latest kubectl version --client
          
          echo "Testing kubectl can show help..."
          docker run --rm kubectl-image:latest kubectl --help
          
          echo "✅ All tests passed"
